//
//  RUSportsPlayerCell_Private.h
//  Rutgers
//
//  Created by Kyle Bailey on 8/21/14.
//  Copyright (c) 2014 Rutgers. All rights reserved.
//

#import "RUSportsPlayerCell.h"

#define SELECTED_SCALE_FACTOR 2.2
#define SMALL_SELECTED_SCALE_FACTOR 1.75

#define IMAGE_CLIPPED_HEIGHT 48

#define IMAGE_HEIGHT 96
#define IMAGE_WIDTH (3.0/4.0*IMAGE_HEIGHT)

#define IMAGE_TOP_CONSTRAINT 7

#define SELECTED_IMAGE_CLIPPED_HEIGHT IMAGE_CLIPPED_HEIGHT*SELECTED_SCALE_FACTOR
#define SELECTED_IMAGE_CLIPPED_WIDTH IMAGE_CLIPPED_HEIGHT*SELECTED_SCALE_FACTOR*0.9

#define SELECTED_IMAGE_HEIGHT IMAGE_HEIGHT*SMALL_SELECTED_SCALE_FACTOR
#define SELECTED_IMAGE_WIDTH IMAGE_WIDTH*SMALL_SELECTED_SCALE_FACTOR

#define SELECTED_IMAGE_TOP_CONSTRAINT IMAGE_TOP_CONSTRAINT*SMALL_SELECTED_SCALE_FACTOR

@interface RUSportsPlayerCell ()
@property UIView *playerView;
@end
