platform :ios, '7.0'

pod 'AFNetworking', '~> 2.2.0'
pod 'XMLDictionary', '~> 1.4.0'
pod 'UIView+AutoLayout'
pod 'TOWebViewController'
pod 'HexColors'
pod 'Shimmer'
pod 'MWFeedParser/NSString+HTML' 
pod 'MWFeedParser/NSDate+InternetDateTime'
pod 'JASidePanels'